# Generated by Django 3.2 on 2024-04-09 10:54

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locum',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appAdmin.customuser')),
                ('title', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('smartcard_number', models.CharField(blank=True, max_length=20)),
                ('gmc_number', models.CharField(blank=True, max_length=20)),
                ('gmc_certificate', models.FileField(blank=True, upload_to='documents/')),
                ('gphc_number', models.CharField(blank=True, max_length=20)),
                ('qualified_date', models.DateField(blank=True)),
                ('nmc_number', models.CharField(blank=True, max_length=20)),
                ('nmc_certificate', models.FileField(blank=True, upload_to='documents/')),
                ('can_provide_references', models.BooleanField(blank=True, default=False)),
                ('passport_copy', models.FileField(blank=True, upload_to='documents/')),
                ('passport_expiry_date', models.DateField(blank=True)),
                ('visa_residence_permit', models.FileField(blank=True, upload_to='documents/')),
                ('dbs_enhanced_disclosure', models.FileField(blank=True, upload_to='documents/')),
                ('dbs_service_number', models.CharField(blank=True, max_length=20)),
                ('safeguarding_level2', models.FileField(blank=True, upload_to='documents/')),
                ('insurance', models.FileField(blank=True, upload_to='documents/')),
                ('insurance_expiry_date', models.DateField(blank=True)),
                ('qualification_certificate', models.FileField(blank=True, upload_to='documents/')),
                ('accreditations1', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('accreditations2', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('accreditations3', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('accreditations4', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('accreditations5', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('accreditations6', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('accreditations7', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('accreditations8', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('accreditations9', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('accreditations10', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('accreditations11', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('accreditations12', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('accreditations13', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('accreditations14', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('accreditations15', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('appAdmin.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
