# Generated by Django 3.2 on 2024-04-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0001_initial'),
        ('locum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=100)),
                ('distance_range', models.DecimalField(decimal_places=2, max_digits=5)),
                ('post_code', models.CharField(max_length=20)),
                ('pharmacist_required', models.BooleanField(default=False)),
                ('technician_required', models.BooleanField(default=False)),
                ('dispenser_required', models.BooleanField(default=False)),
                ('nurse_required', models.BooleanField(default=False)),
                ('anp_nurse_required', models.BooleanField(default=False)),
                ('gp_required', models.BooleanField(default=False)),
                ('locum_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('expenses_offered', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_required', models.DateField()),
                ('times_required', models.CharField(max_length=255)),
                ('any_other_information', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('applied_status', models.BooleanField(default=False)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.employer')),
                ('locum', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locum.locum')),
            ],
        ),
    ]
