# Generated by Django 3.2 on 2024-04-09 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locum', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocumAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timings', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('proximity_range_km', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('locum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locum.locum')),
            ],
            options={
                'ordering': ['date', 'timings'],
            },
        ),
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('negotiation', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locum.job')),
                ('locum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locum.locum')),
            ],
        ),
    ]
