# Generated by Django 3.2 on 2024-04-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locum', '0004_auto_20240415_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='locum',
            name='user_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
