# Generated by Django 3.2 on 2024-04-15 13:40

from django.db import migrations, models
import locum.models


class Migration(migrations.Migration):

    dependencies = [
        ('locum', '0005_locum_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locum',
            name='accreditations1',
            field=models.FileField(blank=True, null=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='accreditations10',
            field=models.FileField(blank=True, null=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='accreditations11',
            field=models.FileField(blank=True, null=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='accreditations12',
            field=models.FileField(blank=True, null=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='accreditations13',
            field=models.FileField(blank=True, null=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='accreditations14',
            field=models.FileField(blank=True, null=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='accreditations15',
            field=models.FileField(blank=True, null=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='accreditations2',
            field=models.FileField(blank=True, null=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='accreditations3',
            field=models.FileField(blank=True, null=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='accreditations4',
            field=models.FileField(blank=True, null=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='accreditations5',
            field=models.FileField(blank=True, null=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='accreditations6',
            field=models.FileField(blank=True, null=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='accreditations7',
            field=models.FileField(blank=True, null=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='accreditations8',
            field=models.FileField(blank=True, null=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='accreditations9',
            field=models.FileField(blank=True, null=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='dbs_enhanced_disclosure',
            field=models.FileField(blank=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='gmc_certificate',
            field=models.FileField(blank=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='insurance',
            field=models.FileField(blank=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='nmc_certificate',
            field=models.FileField(blank=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='passport_copy',
            field=models.FileField(blank=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='qualification_certificate',
            field=models.FileField(blank=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='safeguarding_level2',
            field=models.FileField(blank=True, upload_to=locum.models.UserDocumentPath()),
        ),
        migrations.AlterField(
            model_name='locum',
            name='visa_residence_permit',
            field=models.FileField(blank=True, upload_to=locum.models.UserDocumentPath()),
        ),
    ]
