# Generated by Django 3.2 on 2024-04-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locum', '0006_auto_20240415_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locum',
            name='qualified_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
