# Generated by Django 3.2 on 2024-04-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locum', '0007_alter_locum_qualified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locum',
            name='dbs_service_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='locum',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
