# Generated by Django 3.2 on 2024-04-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locum', '0008_auto_20240415_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locum',
            name='gphc_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
