# Generated by Django 3.2 on 2024-04-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locum', '0009_alter_locum_gphc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locum',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
