# Generated by Django 3.2 on 2024-04-22 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locum', '0010_alter_locum_insurance_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date_required',
        ),
        migrations.RemoveField(
            model_name='job',
            name='distance_range',
        ),
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
