# Generated by Django 3.2 on 2024-04-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locum', '0011_auto_20240422_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='applied_date',
            field=models.DateField(auto_now_add=True, default='2024-02-02'),
            preserve_default=False,
        ),
    ]
