# Generated by Django 3.2 on 2024-04-25 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locum', '0012_appliedjob_applied_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjob',
            name='applied_date',
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
