# Generated by Django 3.2 on 2024-04-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locum', '0013_auto_20240425_1909'),
    ]

    operations = [
    ]
