# Generated by Django 3.2 on 2024-04-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locum', '0014_auto_20240425_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
