# Generated by Django 3.2 on 2024-04-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locum', '0015_appliedjob_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='locum',
            name='gmc_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locum',
            name='gphc_number_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locum',
            name='nmc_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locum',
            name='visa_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
