# Generated by Django 4.2 on 2024-05-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locum', '0017_job_agency_fee_job_booked_by_job_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locumavailability',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locumavailability',
            name='proximity_range_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=5, null=True),
        ),
    ]
