# Generated by Django 4.2 on 2024-06-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locum', '0018_alter_locumavailability_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='discrete_dates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
