# Generated by Django 4.2 on 2024-08-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locum', '0019_job_discrete_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='branch_no',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
