# Generated by Django 4.2 on 2024-12-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locum', '0020_job_branch_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='locum',
            name='is_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
