# Generated by Django 4.2 on 2025-01-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locum', '0021_locum_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='do_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='optometrist_required',
            field=models.BooleanField(default=False),
        ),
    ]
