# Generated by Django 4.2 on 2025-09-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locum', '0022_job_do_required_job_optometrist_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='locum',
            name='no_reference_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locum',
            name='previous_ref_branch_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locum',
            name='previous_ref_manager_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='locum',
            name='previous_ref_manager_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locum',
            name='previous_ref_manager_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='locum',
            name='recent_ref_branch_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locum',
            name='recent_ref_manager_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='locum',
            name='recent_ref_manager_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locum',
            name='recent_ref_manager_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
