# Generated by Django 4.2 on 2025-09-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locum', '0023_locum_no_reference_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locum',
            name='previous_ref_last_worked',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locum',
            name='recent_ref_last_worked',
            field=models.DateField(blank=True, null=True),
        ),
    ]
