# Generated by Django 3.2 on 2024-04-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0002_alter_admin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
