# Generated by Django 3.2 on 2024-04-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0003_alter_admin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'permissions': [('can_register_employer', 'Can register employer'), ('can_delete_locum', 'Can delete locum'), ('can_register_staff', 'Can register staff')]},
        ),
    ]
