# Generated by Django 4.2 on 2024-06-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0004_alter_admin_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
