# Generated by Django 4.2 on 2024-08-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0005_employer_city_employer_post_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTrackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('cc_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('job_ids', models.JSONField(blank=True, default=list)),
                ('invoice_type', models.CharField(max_length=255)),
                ('invoice_no', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='manager_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
